har:
  server:
    web:
      domain: http://192.168.70.7
      projectName: /har-unmanned-mfront
      host: ${har.server.web.domain}${har.server.web.projectName}
      errorPath: ${har.server.web.host}/#/error
      homePath: ${har.server.web.host}/#/home
      indexPath: ${har.server.web.host}/#/index
    front:
      domain: http://192.168.70.7:8082
      projectName: /har-unmanned-mfront
      host: ${har.server.front.domain}${har.server.front.projectName}
